release-date = "2022-12-15"

[[entries]]
id = "ee44a383-b8a4-4236-9cfc-6556ab1f2df2"
type = "breaking change"
description = "remove `find_build_script()` and `iter_script_runners()` functions"
author = "@NiklasRosenstein"

[[entries]]
id = "016452c1-def0-41e2-be99-3861eed9493c"
type = "feature"
description = "add `ProjectFinder` interface and implementations (`CurrentDirectoryProjectFinder` and `GitAwareProjectFinder`)"
author = "@NiklasRosenstein"
